In [1]:
import re

In [2]:
chat1= 'codebasics: you ask a lot of questions 1235678912, abc@xyz.com'
chat2= 'codebasics: here it is : (123)-567-8912, abc@xyz.com'
chat3= 'codebasics: yes, phone: 1235678912 email: abc@xyz.com'

In [13]:
pattern='[a-z0-9A-Z]*@[a-z0-9A-Z*\.[a-zA-Z]*'

matches=re.findall(pattern,chat3)
matches

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\Hp\AppData\Local\Temp\ipykernel_2020\2274129826.py:1: SyntaxWarning: invalid escape sequence '\.'
  pattern='[a-z0-9A-Z]*@[a-z0-9A-Z*\.[a-zA-Z]*'


['abc@xyz.com']

In [14]:
chat1='codebasics: Hello, I am having an issue with my order # 412889912'
chat2='codebasics:I have a problem with my order number 412889912'
chat3='codebasics: My order 412889912 is having an issue, I was charged 300$ when online it says 280$'

In [16]:
pattern='order[^\d]* (\d*)'

matches=re.findall(pattern,chat1)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Hp\AppData\Local\Temp\ipykernel_2020\2547302913.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern='order[^\d]* (\d*)'


['412889912']

In [17]:
text='''Elon Reeve Musk (/ˈiːlɒn mʌsk/; born June 28, 1971) is a businessman known for his key roles in the space company SpaceX and the automotive company Tesla, Inc. He is also known for his ownership of X Corp. (the company that operates the social media platform X, formerly Twitter), and his role in the founding of the Boring Company, xAI, Neuralink, and OpenAI. Musk is the wealthiest individual in the world; as of December 2024, Forbes estimates his net worth to be US$430 billion.[2]

A member of the wealthy South African Musk family, Musk was born in Pretoria and briefly attended the University of Pretoria. At the age of 18 he immigrated to Canada, acquiring its citizenship through his Canadian-born mother, Maye. Two years later, he matriculated at Queen's University in Canada. Musk later transferred to the University of Pennsylvania and received bachelor's degrees in economics and physics. He moved to California in 1995 to attend Stanford University but never enrolled in classes, and with his brother Kimbal co-founded the online city guide software company Zip2. The startup was acquired by Compaq for $307 million in 1999. That same year, Musk co-founded X.com, a direct bank. X.com merged with Confinity in 2000 to form PayPal. In 2002, Musk acquired United States citizenship, and that October eBay acquired PayPal for $1.5 billion. Using $100 million of the money he made from the sale of PayPal, Musk founded SpaceX, a spaceflight services company, in 2002.

In 2004, Musk was an early investor in electric-vehicle manufacturer Tesla Motors, Inc. (later Tesla, Inc.), providing most of the initial financing and assuming the position of the company's chairman. He later became the product architect and, in 2008, the CEO. In 2006, Musk helped create SolarCity, a solar energy company that was acquired by Tesla in 2016 and became Tesla Energy. In 2013, he proposed a hyperloop high-speed vactrain transportation system. In 2015, he co-founded OpenAI, a nonprofit artificial intelligence research company. The following year Musk co-founded Neuralink, a neurotechnology company developing brain–computer interfaces, and the Boring Company, a tunnel construction company. In 2018 the U.S. Securities and Exchange Commission (SEC) sued Musk, alleging that he had falsely announced that he had secured funding for a private takeover of Tesla. To settle the case Musk stepped down as the chairman of Tesla and paid a $20 million fine. In 2022, he acquired Twitter for $44 billion, merged the company into the newly-created X Corp. and rebranded the service as X the following year. In March 2023, Musk founded xAI, an artificial-intelligence company.

Musk's actions and expressed views have made him a polarizing figure. He has been criticized for making unscientific and misleading statements, including COVID-19 misinformation, affirming antisemitic and transphobic comments, and promoting conspiracy theories. His ownership of Twitter has been controversial because of large employee layoffs, an increase in posts containing hate speech, misinformation and disinformation on the website, and changes to website features, including verification.

By early 2024, Musk became active in American politics as a vocal and financial supporter of US presidential candidate Donald Trump, becoming the largest political donor of the 2024 election. After winning the election in November 2024, Trump announced that he had chosen Musk along with Vivek Ramaswamy to co-lead his planned Department of Government Efficiency (DOGE) advisory board, which is tasked with removing regulations in order to reduce expenditures and increase government efficiency.'''

In [18]:
pattern='age(\d+)'

matches=re.findall(pattern,chat1)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Hp\AppData\Local\Temp\ipykernel_2020\2377028231.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern='age(\d+)'


[]

In [19]:
import re

In [21]:
text='''
Joshua rebo number is 9980451765 . revenue is 10 Billion
Teslas CFO number is (999)-123-1479
'''
pattern='/\(\d{3}\)-\d{3}-\d{4}/gm'
matches= re.findall(pattern,text)
matches

<>:5: SyntaxWarning: invalid escape sequence '\('
<>:5: SyntaxWarning: invalid escape sequence '\('
C:\Users\Hp\AppData\Local\Temp\ipykernel_2020\99640134.py:5: SyntaxWarning: invalid escape sequence '\('
  pattern='/\(\d{3}\)-\d{3}-\d{4}/gm'


[]

In [1]:
import spacy

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

In [2]:
nlp=spacy.load("en_core_web_sm")
doc=nlp("Dr Strange loves pav bhaji of Mumbai. Hulk loves chaat of delhi")
for sentence in doc.sents:
    print(sentence)
    
for sentence in doc.sents:
    for word in sentence:
        print(word)

NameError: name 'spacy' is not defined

In [2]:
import nltk

In [5]:
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

sent_tokenize("Dr STrange loves Bhajia")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


['Dr STrange loves Bhajia']

In [6]:
import spacy

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

In [1]:
import spacy

In [2]:
nlp= spacy.blank("en")
doc=nlp("Dr Straneg loves paav bhaji of Mumbai as it costs only $2 per plate")

for token in doc:
    print(token)

Dr
Straneg
loves
paav
bhaji
of
Mumbai
as
it
costs
only
$
2
per
plate


In [3]:
doc= nlp("Tony gave two $ to peter")

In [4]:
token0= doc[0]
token0

Tony

In [5]:
token0.like_num

False

In [6]:
token2=doc[2]
token2.text

'two'

In [7]:
token2.like_num

True

In [8]:
token3=doc[3]
token3.text

'$'

In [9]:
token3.is_currency

True

In [11]:
for token in doc:
    print(token, "==>", "index ", token.i,
          "is_alpha:", token.is_alpha,
          "is_punct:", token.is_punct,
          "like_num:", token.like_num,
          "is_currency:", token.is_currency,)

Tony ==> index  0 is_alpha: True is_punct: False like_num: False is_currency: False
gave ==> index  1 is_alpha: True is_punct: False like_num: False is_currency: False
two ==> index  2 is_alpha: True is_punct: False like_num: True is_currency: False
$ ==> index  3 is_alpha: False is_punct: False like_num: False is_currency: True
to ==> index  4 is_alpha: True is_punct: False like_num: False is_currency: False
peter ==> index  5 is_alpha: True is_punct: False like_num: False is_currency: False


In [12]:
with open ("practice.txt") as f:
    text=f.readlines()
text

FileNotFoundError: [Errno 2] No such file or directory: 'practice.txt'

In [13]:
doc= nlp("gimme double cheese extra large healthy pizza")
tokens=[token.text for token in doc]
tokens

['gimme', 'double', 'cheese', 'extra', 'large', 'healthy', 'pizza']

In [15]:
from spacy.symbols import ORTH
nlp.tokenizer.add_special_case("gimme", [
    {ORTH:"gim",}
    {ORTH: "me"}
])

doc= nlp("gimme double cheese extra large healthy pizza")
tokens=[token.text]

SyntaxError: ':' expected after dictionary key (2860756090.py, line 4)

In [16]:
doc= nlp("Dr STrange loves pav bhaji of Mumbai. Hulk loves chat from delhi")
for sentence in doc.sents:
    print(sentence)

ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: `nlp.add_pipe('sentencizer')`. Alternatively, add the dependency parser or sentence recognizer, or set sentence boundaries by setting `doc[i].is_sent_start`.

In [18]:
nlp.add_pipe('sentencizer')

In [17]:
nlp.pipe_names

[]

In [19]:
doc= nlp("Dr STrange loves pav bhaji of Mumbai. Hulk loves chat from delhi")
for sentence in doc.sents:
    print(sentence)

Dr STrange loves pav bhaji of Mumbai.
Hulk loves chat from delhi


In [6]:
import spacy
nlp= spacy.blank("en")
nlp.add_pipe('sentencizer')
nlp.pipe_names

['sentencizer']

In [7]:

doc=nlp('This is an example text without significant relevance')

In [8]:
for token in doc:
    print(token.text)

This
is
an
example
text
without
significant
relevance


In [9]:
for sentence in doc.sents:
    print(sentence)

This is an example text without significant relevance


In [10]:
for word in doc:
    print(word.text + '-->' + word.pos_)

This-->
is-->
an-->
example-->
text-->
without-->
significant-->
relevance-->


In [12]:
doc=nlp("Tom likes to fly to Australia for holiday.")

for entity in doc.sents:
    print(entity.text + ' - '+ entity.label_ + ' - '+ str(spacy.explain(entity.label_)))

Tom likes to fly to Australia for holiday. -  - None


c:\Users\Hp\anaconda3\Lib\site-packages\spacy\glossary.py:20: UserWarning: [W118] Term '' not found in glossary. It may however be explained in documentation for the corpora used to train the language. Please check `nlp.meta["sources"]` for any relevant links.
  warnings.warn(Warnings.W118.format(term=term))


In [13]:
import spacy

In [14]:
nlp= spacy.blank("en")
doc= nlp("Captain america ate 100$ of samosa. Then he said I can do this all day")

for token in doc:
    print(token)

Captain
america
ate
100
$
of
samosa
.
Then
he
said
I
can
do
this
all
day


In [16]:
nlp.pipe_names

[]

In [21]:
nlp = spacy.load("en_core_web_sm")


In [18]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x19c0da90ad0>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x19c7c22f650>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x19c0dd603c0>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x19c0dd9bd90>),
 ('lemmatizer', <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x19c0dd9be50>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x19c0dd60120>)]

In [22]:

doc= nlp("Captain america ate 100$ of samosa. Then he said I can do this all day")

for token in doc:
    print(token, " | ", token.pos_, " | ", token.lemma_)

Captain  |  PROPN  |  Captain
america  |  PROPN  |  america
ate  |  VERB  |  eat
100  |  NUM  |  100
$  |  NUM  |  $
of  |  ADP  |  of
samosa  |  PROPN  |  samosa
.  |  PUNCT  |  .
Then  |  ADV  |  then
he  |  PRON  |  he
said  |  VERB  |  say
I  |  PRON  |  I
can  |  AUX  |  can
do  |  VERB  |  do
this  |  PRON  |  this
all  |  DET  |  all
day  |  NOUN  |  day


In [23]:
doc= nlp("Tesla Inc is going to acquire twitter for $45 bilion")

for ent in doc.ents:
    print(ent.text, "|", ent.label_,spacy.explain(ent.label_))

Tesla Inc | ORG Companies, agencies, institutions, etc.
$45 bilion | MONEY Monetary values, including unit


In [26]:
from spacy import displacy
displacy.render(doc, style="ent")

In [27]:
import nltk
import spacy

In [28]:
from nltk.stem import PorterStemmer

stemmer= PorterStemmer()

In [30]:
words=['eating', 'eats', 'eat', 'ate', 'adjustable', 'rafting', 'ability', 'meeting']

for word in words:
    print(word, "|", stemmer.stem(word))

eating | eat
eats | eat
eat | eat
ate | ate
adjustable | adjust
rafting | raft
ability | abil
meeting | meet


In [31]:
nlp= spacy.load("en_core_web_sm")

doc= nlp('eating eats eat ate adjustable rafting ability meeting better')

for token in doc:
    print(token, "|", token.lemma_)

eating | eat
eats | eat
eat | eat
ate | eat
adjustable | adjustable
rafting | raft
ability | ability
meeting | meet
better | well


In [32]:
doc= nlp("Bro i dont give a fucking shit")

for token in doc:
    print(token.text, "|", token.lemma_)

Bro | bro
i | I
do | do
nt | not
give | give
a | a
fucking | fucking
shit | shit


In [33]:
import re

In [35]:
print(r'\tTab')

\tTab


In [68]:
text_to_search='''abcdehfgijklmnopqrstuvwxz
1234567890

ABCDEGHIJKKLMNOPQRD

sentence= 'start a sentence and bring it to an end'
Ha HaHa
cat
mat
bat
MetaCharacters(Need to be escaped):

coreyms.com

321-555-3452
123.335.4567
900.335.4567
800.335.4567

Mr.Schafer
Mr Smith

.[{()}\^|*+

Ms Davis

Mrs Schafer
cat
mat
bat


coreymSchafer@gmail.com
corey.schafer@university.edu
corey-321-schafer@may-work.net
'''
sentence= 'start a sentence and bring it to an end'
pattern= re.compile(r'coreyms\.com')

matches= pattern.finditer(text_to_search)

for match in matches:
    print(match)

<re.Match object; span=(168, 179), match='coreyms.com'>


<>:1: SyntaxWarning: invalid escape sequence '\^'
<>:1: SyntaxWarning: invalid escape sequence '\^'
C:\Users\Hp\AppData\Local\Temp\ipykernel_10260\2486206435.py:1: SyntaxWarning: invalid escape sequence '\^'
  text_to_search='''abcdehfgijklmnopqrstuvwxz


In [108]:
sentence= 'Start a sentence and bring it to an end'

pattern= re.compile(r'start', re.IGNORECASE)

matches= pattern.search(sentence)

print(matches)

<re.Match object; span=(0, 5), match='Start'>


In [98]:
emails=''' 
CoreyMSchafer@gmail.com
corey.schafer@university.edu
corey-321-schafer@my-work.net
'''
urls= """ 
https://www.google.com
http://www.legalizeme.site
https://youtube.com"""
pattern=re.compile(r'https?://(www\.)?(\w+)(\.\w+)')

matches=pattern.findurls(urls)

subbed_urls=pattern.sub(r'\2\3',urls)

print(subbed_urls)

 
google.com
legalizeme.site
youtube.com


In [109]:
import string
from nltk.corpus import stopwords

In [110]:
stopwords.words('english')[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [111]:
test_sentence= "This is my foirst string. WOOW we are doing just fine"

In [112]:
no_punctuation= [char for char in test_sentence if char not in string.punctuation]

In [113]:
no_punctuation

['T',
 'h',
 'i',
 's',
 ' ',
 'i',
 's',
 ' ',
 'm',
 'y',
 ' ',
 'f',
 'o',
 'i',
 'r',
 's',
 't',
 ' ',
 's',
 't',
 'r',
 'i',
 'n',
 'g',
 ' ',
 'W',
 'O',
 'O',
 'W',
 ' ',
 'w',
 'e',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'd',
 'o',
 'i',
 'n',
 'g',
 ' ',
 'j',
 'u',
 's',
 't',
 ' ',
 'f',
 'i',
 'n',
 'e']

In [115]:
no_punctuation=''.join(no_punctuation)
no_punctuation

'This is my foirst string WOOW we are doing just fine'

In [116]:
no_punctuation.split()

['This',
 'is',
 'my',
 'foirst',
 'string',
 'WOOW',
 'we',
 'are',
 'doing',
 'just',
 'fine']

In [117]:
clean_sentence= [word for word in no_punctuation.split() if word.lower() not in stopwords.words('english')]

In [118]:
clean_sentence

['foirst', 'string', 'WOOW', 'fine']

In [119]:
from sklearn.datasets import load_digits

In [120]:
digits_dataset= load_digits()

In [121]:
digits_dataset.DESCR

".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 1797\n:Number of Attributes: 64\n:Attribute Information: 8x8 image of integer pixels in the range 0..16.\n:Missing Attribute Values: None\n:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n:Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted in each bl

In [122]:
type(digits_dataset)

sklearn.utils._bunch.Bunch

In [123]:
digits_dataset.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [124]:
from sklearn.feature_extraction.text import CountVectorizer

In [125]:
vectorizer=CountVectorizer()

In [126]:
document1= "Hi How are you"
document2= 'Today is a fantasic day'
document3= 'This was ana mazing experience'

In [128]:
listofdocuments=[document1,document2, document3]
bag_of_words= vectorizer.fit(listofdocuments)

In [129]:
bag_of_words

CountVectorizer()

In [130]:
bag_of_words= vectorizer.transform(listofdocuments)

In [132]:
print (bag_of_words)

  (0, 1)	1
  (0, 5)	1
  (0, 6)	1
  (0, 12)	1
  (1, 2)	1
  (1, 4)	1
  (1, 7)	1
  (1, 10)	1
  (2, 0)	1
  (2, 3)	1
  (2, 8)	1
  (2, 9)	1
  (2, 11)	1


In [134]:
print(vectorizer.vocabulary_.get('very'))

None


In [136]:
print(vectorizer.vocabulary_.get('fantasic'))

4


In [137]:
import pandas as pd
import string 
from pprint import pprint
from time import time

In [138]:
import spacy

In [139]:
nlp=spacy.load("en_core_web_sm")

In [143]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [142]:
doc=nlp("Elon flew to Mars and carried bhajia masala rice with him")

for token in doc:
    print(token, "|", token.pos_, "|", spacy.explain(token.pos_))

Elon | PROPN | proper noun
flew | VERB | verb
to | ADP | adposition
Mars | PROPN | proper noun
and | CCONJ | coordinating conjunction
carried | VERB | verb
bhajia | ADJ | adjective
masala | NOUN | noun
rice | NOUN | noun
with | ADP | adposition
him | PRON | pronoun


In [150]:
doc= nlp("Wow Dr Strange made 265million$ on the very first day")

for token in doc:
    print(token, "|", token.pos_, "|", spacy.explain(token.pos_), "|",
          token.tag_, "|", spacy.explain(token.tag_))

Wow | INTJ | interjection | UH | interjection
Dr | PROPN | proper noun | NNP | noun, proper singular
Strange | PROPN | proper noun | NNP | noun, proper singular
made | VERB | verb | VBD | verb, past tense
265million$ | NUM | numeral | CD | cardinal number
on | ADP | adposition | IN | conjunction, subordinating or preposition
the | DET | determiner | DT | determiner
very | ADV | adverb | RB | adverb
first | ADJ | adjective | JJ | adjective (English), other noun-modifier (Chinese)
day | NOUN | noun | NN | noun, singular or mass


In [154]:
doc=nlp("He quits the job")

doc[3]

print(doc[3].text, "|", doc[3].tag, '|', spacy.explain(doc[3].tag_))

job | 15308085513773655218 | noun, singular or mass


In [155]:
import spacy

nlp= spacy.load("en_core_web_sm")

In [156]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [165]:
doc= nlp(" Tesla is going to acquire TwitterInc for $45 billion")

for ent in doc.ents:
    print(ent.text, "|", ent.label_, "| ", spacy.explain(ent.label_))

Tesla | ORG |  Companies, agencies, institutions, etc.
TwitterInc | ORG |  Companies, agencies, institutions, etc.
$45 billion | MONEY |  Monetary values, including unit


In [166]:
from spacy import displacy

displacy.render(doc, style="ent")

In [167]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [170]:
doc= nlp(" Michael Bloomberg founded BloombergInc in 1982")

for ent in doc.ents:
    print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

Michael Bloomberg | PERSON | People, including fictional
BloombergInc | ORG | Companies, agencies, institutions, etc.
1982 | DATE | Absolute or relative dates or periods


In [171]:
doc= nlp("Tesla is going to acquire Twitter for $45 billion")

for ent in doc.ents:
    print(ent.text, "|", ent.label_)

Tesla | ORG
Twitter | PERSON
$45 billion | MONEY


In [172]:
doc[2:5]

going to acquire

In [173]:
from spacy.tokens import Span

In [174]:
s1= Span(doc, 0,1, label="ORG")
s2= Span(doc, 5,6, label="ORG")

doc.set_ents([s1,s2], default='unmodified')

In [175]:
for ent in doc.ents:
    print(ent.text, "|", ent.label_)

Tesla | ORG
Twitter | ORG
$45 billion | MONEY


In [176]:
import pandas as pd
import numpy as np

In [177]:
df= pd.read_csv("C:\\Users\\Hp\\Downloads\\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [178]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [181]:
df['spam']= df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [182]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [183]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(df.Message, df.spam, test_size=0.2 )

In [184]:
X_test.shape

(1115,)

In [185]:
X_train.shape

(4457,)

In [189]:
from sklearn.feature_extraction.text import CountVectorizer

In [193]:
v= CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7874 sparse matrix of type '<class 'numpy.int64'>'
	with 59319 stored elements in Compressed Sparse Row format>

In [195]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [196]:
X_train_cv.shape

(4457, 7874)

In [199]:
v.get_feature_names_out()[1000:1050].shape

(50,)

In [200]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [201]:
v.vocabulary_

{'can': 1656,
 'you': 7832,
 'tell': 6873,
 'shola': 6218,
 'to': 7048,
 'please': 5344,
 'go': 3205,
 'college': 1922,
 'of': 4976,
 'medicine': 4494,
 'and': 979,
 'visit': 7426,
 'the': 6930,
 'academic': 779,
 'department': 2278,
 'secretary': 6090,
 'what': 7599,
 'current': 2143,
 'situation': 6306,
 'is': 3808,
 'ask': 1112,
 'if': 3654,
 'she': 6186,
 'transfer': 7136,
 'there': 6946,
 'should': 6233,
 'someone': 6416,
 'check': 1779,
 'sagamu': 5993,
 'for': 2981,
 'same': 6011,
 'thing': 6958,
 'lautech': 4102,
 'its': 3826,
 'vital': 7429,
 'completes': 1962,
 'her': 3462,
 'medical': 4493,
 'education': 2563,
 'in': 3699,
 'nigeria': 4860,
 'less': 4149,
 'expensive': 2756,
 'much': 4714,
 'unless': 7287,
 'will': 7642,
 'be': 1291,
 'getting': 3166,
 'citizen': 1843,
 'rates': 5684,
 'new': 4841,
 'zealand': 7860,
 'am': 949,
 'not': 4911,
 'working': 7717,
 'but': 1600,
 'up': 7303,
 'eyes': 2777,
 'philosophy': 5281,
 'so': 6399,
 'text': 6904,
 'later': 4094,
 'when': 7

In [202]:
X_train_np= X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [203]:
np.where(X_train_np[0]!=0)

(array([ 779,  979, 1112, 1291, 1656, 1779, 1843, 1922, 1962, 2143, 2278,
        2563, 2756, 2981, 3166, 3205, 3462, 3654, 3699, 3808, 3826, 4102,
        4149, 4493, 4494, 4714, 4841, 4860, 4976, 5344, 5684, 5993, 6011,
        6090, 6186, 6218, 6233, 6306, 6416, 6873, 6930, 6946, 6958, 7048,
        7136, 7287, 7426, 7429, 7599, 7642, 7832, 7860], dtype=int64),)

In [205]:
X_train[:4]

4399    Can you tell Shola to please go to college of ...
1791    Am not working but am up to eyes in philosophy...
1961    Guess what! Somebody you know secretly fancies...
4806                     Sorry for the delay. Yes masters
Name: Message, dtype: object

In [209]:
X_train_np[0][1483]

0

In [210]:
from sklearn.naive_bayes import MultinomialNB

In [211]:
model= MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [212]:
X_test_cv=v.transform(X_test)

In [214]:
from sklearn.metrics import classification_report

In [215]:
y_pred= model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.98      0.94      0.96       155

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [216]:
from sklearn.pipeline import Pipeline

clf= Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])



In [217]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [219]:
y_pred=clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.98      0.94      0.96       155

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [220]:
import spacy

from spacy.lang.en.stop_words import STOP_WORDS


In [221]:
STOP_WORDS

{"'d",
 "'ll",
 "'m",
 "'re",
 "'s",
 "'ve",
 'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'both',
 'bottom',
 'but',
 'by',
 'ca',
 'call',
 'can',
 'cannot',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'four',
 'from',
 'fron

In [222]:
nlp=spacy.load("en_core_web_sm")

doc=nlp("We just opened our wings, the flying part is coming soon")

for token in doc:
    if token.is_stop:
        print(token)

We
just
our
the
part
is


In [235]:
def preprocess(text):
    doc=nlp(text)
    
    
    no_stop_words= (token.text for token in doc if not token.is_stop)
    return " ".join(no_stop_words)

In [225]:
preprocess("Joshua rebo is a man")

<generator object preprocess.<locals>.<genexpr> at 0x0000019C160B65C0>

In [226]:
import pandas as pd
df= pd.read_json("C:\\Users\\Hp\\Desktop\\combined.json", lines=True)

In [227]:
df.head(5)

id                                              title  \
0     None       Convicted Bomb Plotter Sentenced to 30 Years   
1  12-919   $1 Million in Restitution Payments Announced t...   
2  11-1002  $1 Million Settlement Reached for Natural Reso...   
3   10-015  10 Las Vegas Men Indicted \r\nfor Falsifying V...   
4   18-898  $100 Million Settlement Will Speed Cleanup Wor...   

                                            contents  \
0  PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...   
1    WASHINGTON – North Carolina’s Waccamaw River...   
2        BOSTON– A $1-million settlement has been...   
3    WASHINGTON—A federal grand jury in Las Vegas...   
4  The U.S. Department of Justice, the U.S. Envir...   

                        date         topics  \
0  2014-10-01T00:00:00-04:00             []   
1  2012-07-25T00:00:00-04:00             []   
2  2011-08-03T00:00:00-04:00             []   
3  2010-01-08T00:00:00-05:00             []   
4  2018-07-09T00:00:00-04:00  [Environment]   

                                     components  
0            [National Security Division (NSD)]  
1  [Environment and Natural Resources Division]  
2  [Environment and Natural Resources Division]  
3  [Environment and Natural Resources Division]  
4  [Environment and Natural Resources Division]

In [228]:
type(df.topics[0])

list

In [230]:
df.describe()

id                                              title  \
count    12810                                              13087   
unique   12672                                              12887   
top     13-526  Northern California Real Estate Investor Agree...   
freq         3                                                  8   

                                                 contents  \
count                                               13087   
unique                                              13080   
top       WASHINGTON – ING Bank N.V., a financial inst...   
freq                                                    2   

                             date topics           components  
count                       13087  13087                13087  
unique                       2400    253                  810  
top     2018-04-13T00:00:00-04:00     []  [Criminal Division]  
freq                           20   8399                 2680

In [231]:
df=df[df['topics'].str.len()!=0]

df.head(5)

id                                              title  \
4    18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7   14-1412  14 Indicted in Connection with New England Com...   
19  17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22  15-1562  21st Century Oncology to Pay $19.75 Million to...   
23  17-1404  21st Century Oncology to Pay $26 Million to Se...   

                                             contents  \
4   The U.S. Department of Justice, the U.S. Envir...   
7   A 131-count criminal indictment was unsealed t...   
19  The United States Attorney’s Office for the Mi...   
22  21st Century Oncology LLC, has agreed to pay $...   
23  21st Century Oncology Inc. and certain of its ...   

                         date                                 topics  \
4   2018-07-09T00:00:00-04:00                          [Environment]   
7   2014-12-17T00:00:00-05:00                  [Consumer Protection]   
19  2017-12-14T00:00:00-05:00                          [Environment]   
22  2015-12-18T00:00:00-05:00  [False Claims Act, Health Care Fraud]   
23  2017-12-12T00:00:00-05:00  [Health Care Fraud, False Claims Act]   

                                           components  
4        [Environment and Natural Resources Division]  
7                                    [Civil Division]  
19  [Environment and Natural Resources Division, U...  
22                                   [Civil Division]  
23           [Civil Division, USAO - Florida, Middle]

In [232]:
df.shape

(4688, 6)

In [233]:
df=df.head(100)
df.shape

(100, 6)

In [234]:
len(df['contents'].iloc[4])

5504

In [236]:
df['contents_new']=df['contents'].apply(preprocess)
df.head(5)

id                                              title  \
4    18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7   14-1412  14 Indicted in Connection with New England Com...   
19  17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22  15-1562  21st Century Oncology to Pay $19.75 Million to...   
23  17-1404  21st Century Oncology to Pay $26 Million to Se...   

                                             contents  \
4   The U.S. Department of Justice, the U.S. Envir...   
7   A 131-count criminal indictment was unsealed t...   
19  The United States Attorney’s Office for the Mi...   
22  21st Century Oncology LLC, has agreed to pay $...   
23  21st Century Oncology Inc. and certain of its ...   

                         date                                 topics  \
4   2018-07-09T00:00:00-04:00                          [Environment]   
7   2014-12-17T00:00:00-05:00                  [Consumer Protection]   
19  2017-12-14T00:00:00-05:00                          [Environment]   
22  2015-12-18T00:00:00-05:00  [False Claims Act, Health Care Fraud]   
23  2017-12-12T00:00:00-05:00  [Health Care Fraud, False Claims Act]   

                                           components  \
4        [Environment and Natural Resources Division]   
7                                    [Civil Division]   
19  [Environment and Natural Resources Division, U...   
22                                   [Civil Division]   
23           [Civil Division, USAO - Florida, Middle]   

                                         contents_new  
4   U.S. Department Justice , U.S. Environmental P...  
7   131 - count criminal indictment unsealed today...  
19  United States Attorney Office Middle District ...  
22  21st Century Oncology LLC , agreed pay $ 19.75...  
23  21st Century Oncology Inc. certain subsidiarie...

In [238]:
df['contents'].iloc[10][:300]

'The Department of Justice announced today that 3M Company (3M), headquartered in St. Paul, Minnesota, has agreed to pay $9.1 million to resolve allegations that it knowingly sold the dual-ended Combat Arms Earplugs, Version 2 (CAEv2) to the United States military without disclosing defects that hamp'

In [241]:
from sklearn.feature_extraction.text import CountVectorizer

v= CountVectorizer(ngram_range=(1,3))

v.fit(["Thor Hanthandals is loking for a job"])

v.vocabulary_

{'thor': 12,
 'hanthandals': 2,
 'is': 5,
 'loking': 9,
 'for': 0,
 'job': 8,
 'thor hanthandals': 13,
 'hanthandals is': 3,
 'is loking': 6,
 'loking for': 10,
 'for job': 1,
 'thor hanthandals is': 14,
 'hanthandals is loking': 4,
 'is loking for': 7,
 'loking for job': 11}

In [242]:
corpus=['Thor ate pizza',
        'Loki is tall',
        'Loki is eating pizza']


In [243]:
import spacy

In [244]:
nlp= spacy.load("en_core_web_sm")

def preprocess(text):
    doc=nlp(text)
    
    
    filtered_tokens=[]
    
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
        
    return " ".join(filtered_tokens)

preprocess("Loki is eating pizza")



'Loki eat pizza'

In [245]:
corpus_processed=[preprocess(text) for text in corpus]

corpus_processed

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [246]:
v= CountVectorizer(ngram_range=(1,2))

v.fit(corpus_processed)

v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [247]:
v.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [249]:
v.transform(["Hulk ate pizza"]).toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [250]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [251]:
corpus= ['Thor is eating pizza, Loki is eating pizza, ironmane ate pizza today',
         'Apple is announcing new iphone tomorrow',
         'Tesla is annoucning model-3 tomorrow',
         'Google is announcing pixel-9 tomorrow',
         'Microsoft is announcing new surface tomorrow',
         'Amazon is announcing new eco dot tomorrow',
         'I am eating biryanin and you ar eating grapes ',
         'somrhting is amazing']

In [252]:
v= TfidfVectorizer()

transformed_output=v.fit_transform(corpus)
print(v.vocabulary_)

{'thor': 27, 'is': 17, 'eating': 11, 'pizza': 23, 'loki': 18, 'ironmane': 16, 'ate': 8, 'today': 28, 'apple': 6, 'announcing': 5, 'new': 21, 'iphone': 15, 'tomorrow': 29, 'tesla': 26, 'annoucning': 4, 'model': 20, 'google': 13, 'pixel': 22, 'microsoft': 19, 'surface': 25, 'amazon': 2, 'eco': 12, 'dot': 10, 'am': 0, 'biryanin': 9, 'and': 3, 'you': 30, 'ar': 7, 'grapes': 14, 'somrhting': 24, 'amazing': 1}


In [255]:
all_feature_names=v.get_feature_names_out()

for word in all_feature_names:
    indx= v.vocabulary_.get(word)
    
    print(f"{word}{v.idf_[indx]}")

am2.504077396776274
amazing2.504077396776274
amazon2.504077396776274
and2.504077396776274
annoucning2.504077396776274
announcing1.587786664902119
apple2.504077396776274
ar2.504077396776274
ate2.504077396776274
biryanin2.504077396776274
dot2.504077396776274
eating2.09861228866811
eco2.504077396776274
google2.504077396776274
grapes2.504077396776274
iphone2.504077396776274
ironmane2.504077396776274
is1.1177830356563834
loki2.504077396776274
microsoft2.504077396776274
model2.504077396776274
new1.8109302162163288
pixel2.504077396776274
pizza2.504077396776274
somrhting2.504077396776274
surface2.504077396776274
tesla2.504077396776274
thor2.504077396776274
today2.504077396776274
tomorrow1.4054651081081644
you2.504077396776274


In [256]:
corpus[:2]

['Thor is eating pizza, Loki is eating pizza, ironmane ate pizza today',
 'Apple is announcing new iphone tomorrow']

In [257]:
transformed_output.toarray()[:2]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.23832138, 0.        ,
        0.        , 0.39946384, 0.        , 0.        , 0.        ,
        0.        , 0.23832138, 0.21276627, 0.23832138, 0.        ,
        0.        , 0.        , 0.        , 0.71496415, 0.        ,
        0.        , 0.        , 0.23832138, 0.23832138, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.3419056 , 0.53921481, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.53921481, 0.        , 0.2406975 , 0.        , 0.        ,
        0.        , 0.38995615, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.30264544,
        0.        ]])

In [259]:
import pandas as pd

df= pd.read_csv("C:\\Users\\Hp\\Downloads\\archive (2)\\ecommerceDataset.csv")

In [262]:
import pandas as pd

df= pd.read_csv("C:\\Users\\Hp\\Downloads\\archive (2)\\ecommerceDataset.csv")

In [263]:
df.label.map({
    "Household":0,
    "Books":1,
    "Electronics":2,
    "Clothing & Accessories":3
})

df.head()

AttributeError: 'DataFrame' object has no attribute 'label'

In [5]:
import spacy
 
nlp= spacy.load("en_core_web_lg")

In [ ]:
doc=nlp("dog cat banana afsjljsk kem chho ")

for token in doc:
    print(token.text, "Vector:",token.has_vector,  "OOV:", token.is_oov)

dog Vector: True OOV: False
cat Vector: True OOV: False
banana Vector: True OOV: False
afsjljsk Vector: False OOV: True


In [7]:
doc[0]

dog

In [12]:
base_token=nlp("bread")
base_token[0].vector.shape

(300,)

In [13]:
doc= nlp("sandwich bread car tiger human wheat")

for token in doc:
    print(f"{token.text} <-> {base_token.text}", token.similarity(base_token))

sandwich <-> bread 0.6874560014053445
bread <-> bread 0.9999999766167111
car <-> bread 0.1644114584391833
tiger <-> bread 0.14492353269643002
human <-> bread 0.21103659037655728
wheat <-> bread 0.6572456428272563


In [14]:
def print_similarity(base_word, words_to_compare):
    base_token=nlp(base_word)
    doc=nlp(words_to_compare)
    for token in doc:
        print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

In [18]:
print_similarity("iPhone", "apple samsung")

apple <-> iPhone: 0.6339781147910419
samsung <-> iPhone: 0.6678678014329177


In [19]:
king=nlp.vocab['king'].vector
man= nlp.vocab['man'].vector
woman=nlp.vocab['woman'].vector
queen=nlp.vocab['queen'].vector

result=king-man+woman

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [queen])

array([[0.7880844]], dtype=float32)

In [22]:
import pandas as pd
import numpy as np
df1=pd.read_csv("C:\\Users\\Hp\\Downloads\\archive (3)\\Fake.csv")

In [24]:
df2=pd.read_csv("C:\\Users\\Hp\\Downloads\\archive (3)\\True.csv")

In [27]:
df1['label_num']=df1['label'].map({'Fake':0})

KeyError: 'label'

In [28]:
import gensim

In [32]:
France - Paris+ Berlin = Germany

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (507921125.py, line 1)

In [33]:
import gensim.downloader as api

In [34]:
glv= api.load("glove-twitter-25")

[==================================================] 100.0% 104.8/104.8MB downloaded


In [35]:
glv.doesnt_match('Banana grapes orange human bad'.split())

'grapes'

In [36]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

In [39]:
cosine_similarity([[3,1]],[[6,2]])

array([[1.]])

In [40]:
cosine_distances([[3,1]],[[6,2]])

array([[1.11022302e-16]])

In [41]:
cosine_similarity([[3,1]],[[3,2]])

array([[0.96476382]])

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer


In [2]:
sentences=['I love my dog',
           'I love my cat']

In [3]:
tokenizer=Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)
word_index= tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
sentences=['I love my dog',
           'I love my cat',
           'You love my dog',
           'Do you think my dog is amazing?']

In [7]:
tokenizer= Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index

sequences=tokenizer.texts_to_sequences(sentences)

In [8]:
padded=pad_sequences(sequences)
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[ 0  0  0  5  3  2  4]
 [ 0  0  0  5  3  2  7]
 [ 0  0  0  6  3  2  4]
 [ 8  6  9  2  4 10 11]]
